In [1]:
import pandas as pd 
import numpy as np
import sklearn

In [2]:
df1=pd.read_csv("normal_baseline.txt")

In [3]:
df1.head(20)

    Time_sec  TDS_raw  Turbidity_raw  Flow_L_min
0          0     2745           1953        1.47
1          1     2740           1941        1.47
2          2     2736           1904        1.47
3          3     2737           1895        1.47
4          4     2731           1919        1.47
5          5     2736           1911        1.07
6          6     2739           1919        0.93
7          7     2759           1905        0.93
8          8     2768           1898        0.93
9          9     2769           1902        0.80
10        10     2771           1887        0.93
11        11     2774           1890        1.07
12        12     2787           1901        0.93
13        13     2797           1877        1.07
14        14     2781           1872        0.93
15        15     2821           1877        0.93
16        16     2762           1887        0.93
17        17     2741           1904        0.93
18        18     2745           1888        1.07
19        19     2735           1887        0.93

In [4]:
df1=df1.drop(["Time_sec"],axis=1)

In [5]:
df1=df1.drop(df1.tail(50).index)

In [6]:
df1=df1.drop(df1.tail(2).index)

In [7]:
df1

      TDS_raw  Turbidity_raw  Flow_L_min
0        2745           1953        1.47
1        2740           1941        1.47
2        2736           1904        1.47
3        2737           1895        1.47
4        2731           1919        1.47
...       ...            ...         ...
1113      890           1808        0.67
1114      895           1807        0.53
1115      837           1809        0.53
1116      827           1809        0.40
1117      618           1816        0.27

[1118 rows x 3 columns]

In [8]:
df1["label"]=0

In [9]:
df1

      TDS_raw  Turbidity_raw  Flow_L_min  label
0        2745           1953        1.47      0
1        2740           1941        1.47      0
2        2736           1904        1.47      0
3        2737           1895        1.47      0
4        2731           1919        1.47      0
...       ...            ...         ...    ...
1113      890           1808        0.67      0
1114      895           1807        0.53      0
1115      837           1809        0.53      0
1116      827           1809        0.40      0
1117      618           1816        0.27      0

[1118 rows x 4 columns]

### Smoothing the dataset

In [10]:
window = 5

df1['TDS_smooth'] = df1['TDS_raw'].rolling(window).mean()
df1['Turbidity_smooth'] = df1['Turbidity_raw'].rolling(window).mean()


df1 = df1.dropna()

In [11]:
Q1 = df1['Turbidity_raw'].quantile(0.25)
Q3 = df1['Turbidity_raw'].quantile(0.75)
IQR = Q3 - Q1

df1 = df1[(df1['Turbidity_raw'] >= Q1 - 1.5*IQR) &
        (df1['Turbidity_raw'] <= Q3 + 1.5*IQR)]

In [12]:
df1

      TDS_raw  Turbidity_raw  Flow_L_min  label  TDS_smooth  Turbidity_smooth
53       2731           1808        1.07      0      2728.0            1861.0
54       2748           1811        1.07      0      2731.4            1849.8
88       2723           1840        0.93      0      2698.2            2027.4
94       2101           1655        1.07      0      2570.0            1887.2
95       2098           1674        0.93      0      2451.4            1835.2
...       ...            ...         ...    ...         ...               ...
1113      890           1808        0.67      0       883.2            1810.0
1114      895           1807        0.53      0       888.2            1801.6
1115      837           1809        0.53      0       879.6            1792.0
1116      827           1809        0.40      0       869.0            1798.6
1117      618           1816        0.27      0       813.4            1809.8

[992 rows x 6 columns]

In [13]:
df1=df1.drop(["TDS_raw","Turbidity_raw"],axis=1)

In [14]:
df1

      Flow_L_min  label  TDS_smooth  Turbidity_smooth
53          1.07      0      2728.0            1861.0
54          1.07      0      2731.4            1849.8
88          0.93      0      2698.2            2027.4
94          1.07      0      2570.0            1887.2
95          0.93      0      2451.4            1835.2
...          ...    ...         ...               ...
1113        0.67      0       883.2            1810.0
1114        0.53      0       888.2            1801.6
1115        0.53      0       879.6            1792.0
1116        0.40      0       869.0            1798.6
1117        0.27      0       813.4            1809.8

[992 rows x 4 columns]

In [15]:
df1.isnull().sum()

Flow_L_min          0
label               0
TDS_smooth          0
Turbidity_smooth    0
dtype: int64

## Soap water

In [16]:
df2=pd.read_csv("soap_round_final.txt")

In [17]:
df2 = df2[(df2['TDS_raw'] > 0) & (df2['Turbidity_raw'] > 0) & (df2['Flow_L_min'] >= 0)]

In [18]:
df2

      Time_sec  TDS_raw  Turbidity_raw  Flow_L_min
1            1     2209           1566        1.07
2            2     2203           1662        1.33
3            3     2230           1607        1.20
4            4     2415           1535        1.33
5            5     2353           1499        1.33
...        ...      ...            ...         ...
1181      1181      594           1879        0.00
1182      1182      581           1877        0.00
1183      1183      583           1872        0.00
1184      1184      557           1872        0.00
1185      1185      562           1862        0.00

[1185 rows x 4 columns]

In [19]:
window = 5

df2['TDS_smooth'] = df2['TDS_raw'].rolling(window).mean()
df2['Turbidity_smooth'] = df2['Turbidity_raw'].rolling(window).mean()


df2 = df2.dropna()

In [20]:
df2['label'] = 1

C:\Users\abhia\AppData\Local\Temp\ipykernel_16460\194244534.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['label'] = 1

In [21]:
df2 = df2[df2['Flow_L_min'] > 0.2]

In [22]:
df2

,Time_sec,TDS_raw,Turbidity_raw,Flow_L_min,TDS_smooth,Turbidity_smooth,label
5,5,2353,1499,1.33,2282.0,1573.8,1
6,6,2237,1457,1.33,2287.6,1552.0,1
7,7,2125,1409,1.33,2272.0,1501.4,1
8,8,2096,1397,1.47,2245.2,1459.4,1
9,9,2033,1350,1.33,2168.8,1422.4,1
...,...,...,...,...,...,...,...
1113,1113,1437,2864,0.27,1560.8,2860.2,1
1114,1114,1366,2867,0.27,1499.2,2861.6,1
1115,1115,1235,2843,0.27,1416.8,2857.4,1
1116,1116,1221,2848,0.27,1354.0,2856.8,1
1117,1117,1154,2849,0.27,1282.6,2854.2,1

In [23]:
df2=df2.drop(["Time_sec","TDS_raw","Turbidity_raw"],axis=1)

In [24]:
df2

      Flow_L_min  TDS_smooth  Turbidity_smooth  label
5           1.33      2282.0            1573.8      1
6           1.33      2287.6            1552.0      1
7           1.33      2272.0            1501.4      1
8           1.47      2245.2            1459.4      1
9           1.33      2168.8            1422.4      1
...          ...         ...               ...    ...
1113        0.27      1560.8            2860.2      1
1114        0.27      1499.2            2861.6      1
1115        0.27      1416.8            2857.4      1
1116        0.27      1354.0            2856.8      1
1117        0.27      1282.6            2854.2      1

[1095 rows x 4 columns]

## Soap + Muddy water

In [25]:
df3=pd.read_csv("muddy+soap_anomly.txt")

In [26]:
df3

      Time_sec  TDS_raw  Turbidity_raw  Flow_L_min
0            0     1712           2757         0.0
1            1     1712           2746         0.0
2            2     1717           2750         0.0
3            3     1715           2755         0.0
4            4     1712           2736         0.0
...        ...      ...            ...         ...
1063      1063      907           2025         0.0
1064      1064      901           2209         0.0
1065      1065      899           2144         0.0
1066      1066      889           2191         0.0
1067      1067      890           2192         0.0

[1068 rows x 4 columns]

In [27]:
df3 = df3[(df3['TDS_raw'] > 0) & (df3['Turbidity_raw'] > 0) & (df3['Flow_L_min'] >= 0)]

In [28]:
df3 = df3[df3['Flow_L_min'] > 0.03]
df3 = df3[(df3['TDS_raw'] > 0) & (df3['Turbidity_raw'] > 0)]

In [29]:
df3.tail(50)

      Time_sec  TDS_raw  Turbidity_raw  Flow_L_min
983        983      823           2255        0.53
984        984      811           2257        0.40
985        985      814           2264        0.40
986        986      805           2380        0.53
987        987      806           2419        0.40
988        988      803           2285        0.40
989        989      807           2356        0.27
990        990      806           2368        0.40
991        991      823           2383        0.40
992        992      800           2389        0.27
993        993      815           2398        0.40
994        994      811           2427        0.27
995        995      806           2427        0.40
996        996      817           2421        0.27
997        997      816           2429        0.40
998        998      816           2429        0.27
999        999      816           2419        0.40
1000      1000      818           2422        0.27
1001      1001      792           2399        0.27
1002      1002      799           2256        0.40
1003      1003      800           2246        0.27
1004      1004      797           2233        0.40
1005      1005      793           2226        0.40
1006      1006      789           2253        0.27
1007      1007      801           2215        0.40
1008      1008      824           2266        0.40
1009      1009      851           2240        0.40
1010      1010      849           2260        0.27
1011      1011      883           2226        0.27
1012      1012      859           2238        0.27
1021      1021      859           2515        0.13
1023      1023      854           2512        0.13
1025      1025      873           2503        0.13
1026      1026      878           2276        0.27
1027      1027      881           2272        0.13
1028      1028      880           2249        0.13
1029      1029      893           2229        0.27
1030      1030      885           2229        0.27
1031      1031      901           2217        0.13
1032      1032      910           2555        0.40
1033      1033      911           2461        0.53
1034      1034      912           2607        0.40
1035      1035      913           2640        0.27
1036      1036      906           2688        0.13
1037      1037      912           2717        4.27
1038      1038      901           2723        0.93
1039      1039      903           2731        0.13
1040      1040      901           2751        0.13
1053      1053      899           2256        0.40
1055      1055      887           2111        1.20

In [30]:
window = 5

df3['TDS_smooth'] = df3['TDS_raw'].rolling(window).mean()
df3['Turbidity_smooth'] = df3['Turbidity_raw'].rolling(window).mean()

df3 = df3.dropna()

In [31]:

df3['label'] = 2

In [32]:
df3

,Time_sec,TDS_raw,Turbidity_raw,Flow_L_min,TDS_smooth,Turbidity_smooth,label
55,55,1298,2673,0.13,1344.4,2680.4,2
56,56,1302,2638,0.40,1319.8,2679.4,2
57,57,1294,2626,0.67,1305.6,2676.6,2
58,58,1294,2639,0.53,1296.8,2659.4,2
59,59,1301,2626,0.67,1297.8,2640.4,2
...,...,...,...,...,...,...,...
1038,1038,901,2723,0.93,908.8,2675.0,2
1039,1039,903,2731,0.13,907.0,2699.8,2
1040,1040,901,2751,0.13,904.6,2722.0,2
1053,1053,899,2256,0.40,903.2,2635.6,2
1055,1055,887,2111,1.20,898.2,2514.4,2

In [33]:
df3=df3.drop(["Time_sec","TDS_raw","Turbidity_raw"],axis=1)

In [34]:
df3.head(50)

     Flow_L_min  TDS_smooth  Turbidity_smooth  label
55         0.13      1344.4            2680.4      2
56         0.40      1319.8            2679.4      2
57         0.67      1305.6            2676.6      2
58         0.53      1296.8            2659.4      2
59         0.67      1297.8            2640.4      2
60         0.53      1300.2            2633.8      2
61         0.67      1304.2            2634.0      2
62         0.53      1311.4            2635.0      2
63         0.67      1318.2            2636.6      2
64         0.53      1323.6            2636.6      2
65         0.67      1329.4            2632.0      2
66         0.67      1333.8            2631.6      2
67         0.53      1337.8            2633.4      2
68         0.53      1342.2            2633.0      2
69         0.67      1348.6            2636.4      2
70         0.53      1356.0            2642.4      2
71         0.53      1359.2            2644.0      2
72         0.53      1361.4            2662.6      2
73         0.67      1364.8            2664.8      2
74         0.53      1367.6            2665.2      2
75         0.53      1367.8            2664.2      2
76         0.40      1370.6            2662.0      2
77         0.53      1375.8            2644.6      2
78         0.53      1379.0            2642.8      2
79         0.53      1383.4            2679.0      2
80         0.53      1385.2            2729.0      2
81         0.53      1388.8            2772.4      2
82         0.53      1388.6            2830.8      2
83         0.53      1390.4            2889.0      2
84         0.53      1392.0            2906.6      2
85         0.53      1395.8            2905.4      2
86         0.40      1396.2            2908.2      2
87         0.53      1397.2            2887.0      2
88         0.53      1397.0            2859.4      2
89         0.53      1395.6            2848.2      2
90         0.53      1394.0            2845.2      2
91         0.53      1394.2            2841.6      2
92         0.40      1394.6            2828.8      2
93         0.53      1394.8            2799.6      2
94         0.53      1396.0            2756.2      2
95         0.40      1394.8            2709.4      2
96         0.53      1394.4            2665.2      2
97         0.53      1396.0            2639.0      2
98         0.40      1399.8            2636.2      2
99         0.53      1400.4            2637.0      2
100        0.40      1403.8            2637.0      2
101        0.40      1405.0            2639.8      2
102        0.40      1405.2            2639.8      2
103        0.40      1402.6            2636.6      2
104        0.27      1402.2            2593.8      2

## Final blockage

In [35]:
df4=pd.read_csv("final_bloackage.txt")

In [36]:
df4

     Time_sec  TDS_raw  Turbidity_raw  Flow_L_min
0           0      917           2288        0.93
1           1      915           2315        0.80
2           2      896           2311        0.93
3           3      889           2299        0.93
4           4      894           2384        0.80
..        ...      ...            ...         ...
615       615     1102           1691        0.13
616       616     1101           1697        0.00
617       617     1104           1696        0.13
618       618     1114           1698        0.13
619       619     1104           1698        0.00

[620 rows x 4 columns]

In [37]:
df4 = df4[df4['TDS_raw'] > 300]

In [38]:
window = 5

df4['TDS_smooth'] = df4['TDS_raw'].rolling(window).mean()
df4['Turbidity_smooth'] = df4['Turbidity_raw'].rolling(window).mean()

df4 = df4.dropna()

C:\Users\abhia\AppData\Local\Temp\ipykernel_16460\4284968216.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['TDS_smooth'] = df4['TDS_raw'].rolling(window).mean()
C:\Users\abhia\AppData\Local\Temp\ipykernel_16460\4284968216.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['Turbidity_smooth'] = df4['Turbidity_raw'].rolling(window).mean()

In [39]:
df4

,Time_sec,TDS_raw,Turbidity_raw,Flow_L_min,TDS_smooth,Turbidity_smooth
4,4,894,2384,0.80,902.2,2319.4
5,5,870,2325,0.80,892.8,2326.8
6,6,874,2343,0.80,884.6,2332.4
7,7,878,2358,0.67,881.0,2341.8
8,8,880,2363,0.67,879.2,2354.6
...,...,...,...,...,...,...
615,615,1102,1691,0.13,1178.4,1650.0
616,616,1101,1697,0.00,1127.2,1675.2
617,617,1104,1696,0.13,1101.8,1692.2
618,618,1114,1698,0.13,1103.8,1695.8
619,619,1104,1698,0.00,1105.0,1696.0

In [40]:
df4=df4.drop(["Time_sec","TDS_raw","Turbidity_raw"],axis=1)

In [41]:
df4['label'] = 3

In [46]:
df4.tail(50)

     Flow_L_min  TDS_smooth  Turbidity_smooth  label
569        0.13       886.6            1715.8      3
570        0.13       886.6            1715.8      3
571        0.13       889.0            1715.0      3
572        0.13       888.2            1714.4      3
573        0.27       889.0            1713.0      3
574        0.13       888.0            1711.6      3
575        0.13       889.8            1713.6      3
576        0.13       888.8            1712.0      3
577        0.13       889.2            1712.2      3
578        0.13       888.2            1711.8      3
579        0.13       889.0            1712.4      3
580        0.13       888.0            1709.2      3
581        0.13       890.6            1709.2      3
582        0.13       889.0            1708.2      3
583        0.13       889.6            1707.4      3
584        0.13       890.4            1705.6      3
585        0.13       891.2            1705.0      3
586        0.13       888.2            1704.0      3
587        0.13       887.4            1703.6      3
588        0.13       894.6            1702.2      3
590        0.13       936.6            1701.2      3
591        0.13       984.0            1699.8      3
592        0.13      1038.4            1692.6      3
593        0.13      1127.8            1659.0      3
594        0.13      1211.6            1611.4      3
595        0.13      1261.0            1590.2      3
596        0.13      1306.0            1551.6      3
597        0.13      1346.4            1509.2      3
598        0.13      1350.6            1489.2      3
599        0.13      1351.6            1486.0      3
600        0.13      1350.8            1482.2      3
601        0.13      1349.2            1496.4      3
602        0.13      1348.4            1519.6      3
603        0.13      1348.6            1545.2      3
604        0.13      1349.4            1563.2      3
605        0.13      1347.4            1552.8      3
606        0.13      1348.2            1526.0      3
607        0.27      1348.0            1503.0      3
608        0.13      1345.8            1484.6      3
609        0.13      1342.8            1466.6      3
610        0.13      1343.6            1460.4      3
611        0.13      1344.8            1486.6      3
612        0.13      1321.2            1517.2      3
613        0.13      1274.2            1559.0      3
614        0.13      1226.2            1609.4      3
615        0.13      1178.4            1650.0      3
616        0.00      1127.2            1675.2      3
617        0.13      1101.8            1692.2      3
618        0.13      1103.8            1695.8      3
619        0.00      1105.0            1696.0      3

In [43]:
# df4 = df4.rename(columns={'Flow_L_min': 'Flow_smooth'})

In [44]:
df4

     Flow_L_min  TDS_smooth  Turbidity_smooth  label
4          0.80       902.2            2319.4      3
5          0.80       892.8            2326.8      3
6          0.80       884.6            2332.4      3
7          0.67       881.0            2341.8      3
8          0.67       879.2            2354.6      3
..          ...         ...               ...    ...
615        0.13      1178.4            1650.0      3
616        0.00      1127.2            1675.2      3
617        0.13      1101.8            1692.2      3
618        0.13      1103.8            1695.8      3
619        0.00      1105.0            1696.0      3

[615 rows x 4 columns]

## combining all data classes

In [50]:
import pandas as pd

df= pd.concat([df1, df2, df3, df4], ignore_index=True)

In [51]:
df

      Flow_L_min  label  TDS_smooth  Turbidity_smooth
0           1.07      0      2728.0            1861.0
1           1.07      0      2731.4            1849.8
2           0.93      0      2698.2            2027.4
3           1.07      0      2570.0            1887.2
4           0.93      0      2451.4            1835.2
...          ...    ...         ...               ...
3560        0.13      3      1178.4            1650.0
3561        0.00      3      1127.2            1675.2
3562        0.13      3      1101.8            1692.2
3563        0.13      3      1103.8            1695.8
3564        0.00      3      1105.0            1696.0

[3565 rows x 4 columns]

In [53]:
df= df.sample(frac=1).reset_index(drop=True)

In [54]:
df

      Flow_L_min  label  TDS_smooth  Turbidity_smooth
0           0.27      2       825.6            2532.2
1           0.53      1      1229.0            3100.2
2           0.27      2       899.0            3121.0
3           0.27      2       816.6            2424.0
4           1.33      0       934.2            1662.2
...          ...    ...         ...               ...
3560        0.93      0       131.4            1777.2
3561        0.27      2       979.0            2426.8
3562        1.33      0       979.8            1738.6
3563        0.27      2      1030.4            2704.0
3564        0.27      2      1209.6            2549.6

[3565 rows x 4 columns]

In [58]:
df = df[df['TDS_smooth'] > 200]

In [59]:
df

      Flow_L_min  label  TDS_smooth  Turbidity_smooth
0           0.27      2       825.6            2532.2
1           0.53      1      1229.0            3100.2
2           0.27      2       899.0            3121.0
3           0.27      2       816.6            2424.0
4           1.33      0       934.2            1662.2
...          ...    ...         ...               ...
3559        0.27      2       811.0            2393.0
3561        0.27      2       979.0            2426.8
3562        1.33      0       979.8            1738.6
3563        0.27      2      1030.4            2704.0
3564        0.27      2      1209.6            2549.6

[3545 rows x 4 columns]

In [ ]:
# df.to_csv("final_data.csv", index=False)